name: Deploy Package to Development

on:
  push:
    branches:
      - development

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --force

      - name: Setup .env
        run: |
          echo "WALLET_CONNECT_PROJECT_ID=${{ secrets.WALLET_CONNECT_PROJECT_ID }}" > .env

      - name: Build
        run: |
          echo ${{ secrets.DEVNET_CONFIG }} | base64 -d > hyperchains/config.json
          npm run generate:node:hyperchain

      - name: Push Build to S3 Bucket
        run: |
          aws s3 sync dist s3://${{ secrets.DEVNET_PORTAL_BUCKET }} --delete

      - name: Invalidate CloudFront Distribution
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DEVNET_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
